name: ci

on: [ push, pull_request ]

jobs:
  server-job:
    runs-on: ubuntu-latest # Choosing OS
    container:
      image: postman/newman
      
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'
    - run: npm i

#    - name: install newman
#      run: npm i newman

    - name: run backend
      run: node server.js &

    - name: Run API Tests
    # trying to run tests
      run: newman run JWT.postman_collection.json
